config/routes.rb
Fanfollow::Application.routes.draw do
  root :to => "home#landingpage"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  #Omniauth stuff!
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to:'sessions#destroy'
  
  resources :events
  resources :cars
  resources :rides
  resources :passengers
end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :rides
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @events = Event.find(params[:id])
    @event = Event.find(params[:id])
    @ride = Event.find(params[:id])
    @rides = Ride.all
    @current_user = current_user
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    # If you want to store who created this event, write @event.user_id = current_user.id
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to root_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :image_id, :date, :location)
  end

end

app/views/events/_form.html.erb
<center>
<%= form_for @event do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.label :description %>
  <%= f.text_field :description %><br />

  <%= f.label :image_id %>
  <%= f.text_field :image_id %><br />

  <%= f.label :date %>
  <%= f.text_field :date %><br />

  <%= f.label :location %>
  <%= f.text_field :location %><br />

  <%= f.submit %>
<% end %>
</center>

app/views/events/edit.html.erb
<h1>Edit Your Event!</h1>
<%= render "form" %>

app/views/events/index.html.erb
   <%= stylesheet_link_tag "polaroid.css" %>

<center><h1>Events - What the fluke Murph?!</h1>
<h3>Check out these crunchy events</h3></center>
  
<!-- Polaroid gallery -->
<div class="row">
  <div class="large-12 columns" style="overflow: visible">
    <ul class="polaroids large-block-grid-4 small-block-grid-2"> 
      <h4>
          <% @events.each do |event| %>
            <li>
              <a href="/events/<%= event.id %>" title="<%= event.name %>" location=", <%= event.location %>">
              <img alt="<%= event.name %>" src="<%= event.image_id %>" /> 
              </a>
            </li>
          <% end %>        
      </h4>
    </ul>
  </div>
</div>
<!-- /Polaroid gallery -->

  
  <center><a href="/events/new" class="btn btn-primary btn-lg"><i class="icon-white icon-road"></i> Create Event</a></center>
  


  <!-- If you want to check if they are a user first, use: -->
  <!-- add current_user? -->
  <!-- see https://github.com/plataformatec/devise for doc. -->

app/views/events/new.html.erb
<h1>Add Your Event!</h1>
<%= render "form" %>

app/views/events/show.html.erb
<center>
<h1>
  <%= @event.name %><br>
</h1>
<h4>
  <%= @event.description %><br/>
  <center> <%= @event.location %><br/><br/></center>
</h4>
 <img alt="<%= @event.name %>" src="<%= @event.image_id %>"  height="500" width="500"/> 

<%= stylesheet_link_tag "stylish-portfolio.css" %>
    <%= stylesheet_link_tag "polaroid.css" %>
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">

<br/><br/>

<center>


<!-- <em><strong> Or  </em></strong> -->



<% edit_event_button = '<div class="btn btn-primary btn-warning"><span class="glyphicon glyphicon-headphones"></span><h2>Edit event</h2></div>'.html_safe %>

<% add_ride_button = '<div class="btn btn-primary btn-success"><span class="glyphicon glyphicon-road"></span><h2>Add a ride</h2></div>'.html_safe %>


    <%=
     link_to_if(@current_user.nil?, add_ride_button, { controller: "devise/sessions", action: "create"}) do
       link_to(add_ride_button, { controller: "rides", action: "new", event_id: @event.id })
     end
  %>

  <%=
     link_to_if(@current_user.nil?, edit_event_button, { controller: "devise/sessions", action: "create"}) do
       link_to(edit_event_button, { controller: "events", action: "edit", event_id: @event.id })
     end
  %>
</center>


<% ride_count = 0 %>
<center><h2>Or join a ride:</h2>
 <% @rides.each do |ride| %><h3>
    <% if ride.event_id == @event.id %>
      <% ride_count = ride_count + 1 %>
      <%= ride_count %>.
      <%= link_to ride.ride_name, ride_path(ride) %>
      <br/></h3>
    <% end %>
  <% end %>

  <center>

<br/>

</center>

</center>
</center>