config/routes.rb
Fanfollow::Application.routes.draw do
  root :to => "home#landingpage"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  #Omniauth stuff!
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to:'sessions#destroy'
  
  resources :events
  resources :cars
  resources :rides
  resources :passengers
end

app/models/ride.rb
class Ride < ActiveRecord::Base

  has_many :passengers
  belongs_to :car
  belongs_to :event

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  def show
    @ride = Ride.find(params[:id])
    @event = Event.all
    @passengers = Passenger.all
  end

  def index
    @ride = Ride.all
  end

  def new
      @ride = Ride.new(params[:ride_params])
      @event = Event.find(params[:event_id])
      @user = current_user.id
      @cars = Car.all
  end

  def create
    @ride = Ride.new(ride_params)
    if @ride.save
      redirect_to @ride
    else
      render 'new'
    end
  end

  def edit
    @ride = Ride.find(params[:id])
  end

  def update
    @ride = Ride.find(params[:id])
    @ride.update(ride_params)
    redirect_to root_path
  end

  def destroy
    @ride = Ride.find(params[:id])
    @ride.destroy
    redirect_to root_path
  end

  private
  def ride_params
    params.require(:ride).permit(:car_id, :ride_name, :event_id)
  end

end

app/views/rides/_form.html.erb
  <h3><%= "Create a ride for " + @event.name %></h3>
      


<!-- Polaroid gallery -->
<div class="row">
  <div class="large-08 columns" style="overflow: visible">
    <ul class="polaroids large-block-grid-4 small-block-grid-2"> 
      <h4>
            
              <a href="/events/<%= @event.id %>" title="<%= @event.name %>" location=", <%= @event.location %>">
              <img alt="<%= @event.name %>" src="<%= @event.image_id %>" height="500" width="500"/> 
              </a>
            
      </h4>
    </ul>
  </div>
</div>
<!-- /Polaroid gallery -->
<center>
<!-- <p>Here's your car:</p><br>

  <% @cars.each do |car| %>
    <% if car.user_id == @user %>
      <%= car.name %>
      <br/>
    <% end %>
  <% end %>

<p>If not click "Add a New Car" for this ride.
</p>
    <%= link_to "Create a new car", new_car_path %>
 -->

<% @selected_car_id = 1 %>


<%= form_for @ride do |f| %>
  <%= f.label :name_your_ride %>
  <%= f.text_field :ride_name %>
  <br/>
  
  <%= f.hidden_field :car_id, :value => @selected_car_id %>
    <%= f.hidden_field :event_id, :value => @event.id %>
  <br/>
  <%= f.submit %>
<% end %>
  

app/views/rides/edit.html.erb
<h1>Edit your ride</h1>
<%= render "form" %>

<%= link_to 'Destroy', post_comment_path(@post, comment),
            :confirm => 'Are you sure?', :method => :delete %>

<!-- This needs to only be accessible by the creator or the admin -->

app/views/rides/new.html.erb
<h1>Add a ride for this event!</h1>
<%= render "form" %>

app/views/rides/show.html.erb
<h1>The ride <%= @ride.ride_name %> is going to <%= @event.find(@ride.event_id).name %></h1>
<center><h3> The folks have seats: </h3>
  
  <h3>
  <% @passengers.each do |passenger| %>
    <% if passenger.ride_id == @ride.id %>
      <%= User.find_by(passenger.user_id).name %>
      <br/>
    <% end %>
  <% end %>

</h3>

<br/>


<h2><b>It's not a party without you! Join us:</b>
<p> <%= link_to 'Reserve a seat', new_passenger_path(:ride_id => @ride.id) %> </p>
</h2>
</center>






<!-- Add Button to Reserve Seat -->